# Generated by Django 3.2.4 on 2022-07-24 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(blank=True, max_length=250)),
                ('article_link', models.CharField(max_length=250)),
                ('article_img', models.CharField(blank=True, max_length=250)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
