# Generated by Django 3.2.4 on 2022-07-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='article_link',
            new_name='article_links',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='article_img',
            new_name='article_titles',
        ),
        migrations.RemoveField(
            model_name='email',
            name='article_title',
        ),
    ]
