# Generated by Django 3.2.4 on 2022-07-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20220729_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='article_descs',
            field=models.CharField(default='', max_length=205),
            preserve_default=False,
        ),
    ]
